DROP PROCEDURE IF EXISTS show_table;
DELIMITER //
CREATE  PROCEDURE `show_table`(IN tab_name VARCHAR(40) )
BEGIN
 SET @t1 =CONCAT('SELECT * FROM ',tab_name );
 PREPARE stmt3 FROM @t1;
 EXECUTE stmt3;
 DEALLOCATE PREPARE stmt3;
END //
DELIMITER ;

